name: Test csv-generator

on:
  push: {}
  pull_request: {}

jobs:
  validate_metrics_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Generate metrics docs
        run: make generate-doc
      - name: Validate no changes
        run: git diff --exit-code

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - name: Install Golang
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Build and Test csv-generator
      run: make container-build && ./tests/e2e-test-csv-generator.sh

  check_commited_files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install Golang
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Check commited files
      run: hack/check-commited-changes.sh
